# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170114_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='seen',
        ),
        migrations.AddField(
            model_name='post',
            name='check_post',
            field=models.ManyToManyField(related_name='check_post', to='blog.Blog'),
        ),
    ]
